#ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

#SpringProperties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
# MailProperties
  mail:
    host: smtp.163.com
    port: 465
    username: 18149318053@163.com
    password: QHMLZWQUVZDQOJSA
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
#redisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
#kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: Community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

#MybatisProperties
mybatis:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fangzhe.community.entity

# communityProperties
community:
  path:
    domain: http://localhost:8080
    upload: d:/work/data/upload
